// <auto-generated />
namespace ShareAVilla.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig50 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig50));
        
        string IMigrationMetadata.Id
        {
            get { return "201711241537069_mig50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
